# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xlwifi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gta4xlwifi)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-P610,71e1487e45cbb17d0e89ba80d2015456ae00e5b1)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-P610,68f963d59bab4c0a30f463f9d942656faad7fee2)
$(call add-radio-file-sha1-checked,radio/models,0a5c3b2cef8f0c09b09f80363601f16491824a89)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-P610,0dbe58c60049a5394de3447358614084b172e501)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-P610,edf7765cd03d7246b7a3593fcb047cb1fe6f03f8)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-P610,b2cc55f350e3cd97ff9252b97ce51d389b03981a)
$(call add-radio-file-sha1-checked,radio/version_SM-P610,97072a89811f8cdebe05ed7944eeb66461f6c01c)

endif
